### ISSUE TITLE
Log files fill up with AddressNotFoundException on private IPv6 addresses

### ISSUE THREAD

**Issue by rdev5** [Torann/laravel-geoip#55]
Cross-references: https://github.com/maxmind/GeoIP2-php/issues/74

Error: `The address ::1 is not in the database.`

I haven't seen any from 127.0.0.1 (IPv4), but GeoIP2 fills up logs very quickly with the above error and stack trace when the error is thrown (discovered by rap2hpoutre/laravel-log-viewer) at https://github.com/maxmind/GeoIP2-php/blob/master/src/Database/Reader.php#L220-L224

Consider adding the following (or a similar implementation) to skip database check if the IP is private:

```
function is_private_IP($ip) {
    return filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4 | FILTER_FLAG_NO_PRIV_RANGE |  FILTER_FLAG_NO_RES_RANGE);
}
```

Source: https://arjunphp.com/check-if-an-ip-address-is-private-with-php/

**Comment by Torann** [comment]
In version 1.0 logging is optional. I for one don't rely on the data from the GeoIP for anything crucial, so the logging is of no use to me. That's why it's not optional.

Also in v1.0 the IP check uses better validation. [GeoIP.php#L246](https://github.com/Torann/laravel-geoip/blob/1.0/src/GeoIP.php#L246)
