### ISSUE TITLE
Feature Request Add freegeoip.net

### ISSUE THREAD

**Issue by ziming** [Torann/laravel-geoip#61]
Add freegeoip.net as 1 of the services. Feature request

**Comment by Torann** [comment]
I looked at this a few weeks ago and decided to not implement it. Freegeoip.net uses the same GeoLite2 data from MaxMind as the [MaxMind Database](http://lyften.com/projects/laravel-geoip/doc/services.html) service. So the data is the same, because of this I would recommend just using the MaxMind Database service. Having it locally would ensure no downtime and you control the database updates with a simple console command.
